import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import toast from "react-hot-toast";
import { getPublicReport, getErrorMessage } from "../services/api";
import LoadingSpinner from "../components/ui/LoadingSpinner";
import VerdictBadge from "../components/ui/VerdictBadge";
import ConfidenceBar from "../components/ui/ConfidenceBar";

const formatDate = (value) => {
  if (!value) return "Unknown";
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(new Date(value));
};

function ReportPage() {
  const { id } = useParams();
  const [report, setReport] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  const fetchReport = async () => {
    try {
      const data = await getPublicReport(id);
      setReport(data);
      setError("");
    } catch (requestError) {
      if (requestError.response?.status === 404) {
        setError("This report does not exist or has been removed");
      } else {
        setError(getErrorMessage(requestError, "Could not load report. Please try again."));
      }
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    document.title = `ScamShield NG — Scam Report #${id?.substring(0, 8)}`;
    fetchReport();
  }, [id]);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    toast.success("Link copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  if (isLoading) {
    return (
      <main className="min-h-screen bg-slate-950 px-4 py-8 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6">
            <LoadingSpinner label="Loading report..." size="lg" />
          </div>
        </div>
      </main>
    );
  }

  if (error) {
    return (
      <main className="min-h-screen bg-slate-950 px-4 py-8 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <div className="text-center py-16">
            <div className="text-6xl mb-4">📄</div>
            <h3 className="text-white text-xl font-medium mb-2">Report Not Found</h3>
            <p className="text-slate-400 mb-6">{error}</p>
            <Link
              to="/"
              className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium transition-colors"
            >
              Go to Home
            </Link>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-3xl">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-2 mb-3">
            <span className="text-slate-400 text-sm">ScamShield NG Report</span>
          </div>
          <h1 className="text-3xl font-bold text-white mb-2">
            Scam Analysis Report
          </h1>
          <p className="text-slate-400">
            This report was generated by ScamShield NG AI on{" "}
            <span className="text-white">{formatDate(report.created_at)}</span>
          </p>
        </div>

        {/* Report Card */}
        <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6 mb-6">
          {/* Large verdict badge centered */}
          <div className="text-center mb-6">
            <VerdictBadge verdict={report.verdict} size="lg" />
          </div>

          {/* Confidence */}
          <div className="mb-4">
            <p className="text-slate-400 text-sm mb-2">Confidence Score</p>
            <ConfidenceBar score={report.confidence_score} />
          </div>

          {/* Message preview */}
          <div className="bg-slate-900 rounded-lg p-4 mb-4 border-l-4 border-blue-500">
            <p className="text-slate-400 text-xs uppercase tracking-wide mb-2">
              Message Analysed
            </p>
            <p className="text-slate-300 text-sm italic">"{report.message_text}"</p>
          </div>

          {/* Analysis details grid */}
          <div className="grid grid-cols-2 gap-4 mb-4">
            {report.scam_category && (
              <div className="bg-slate-900 rounded-lg p-3">
                <p className="text-slate-500 text-xs mb-1">Scam Category</p>
                <p className="text-white text-sm font-medium capitalize">
                  {report.scam_category.replace(/_/g, ' ')}
                </p>
              </div>
            )}
            {report.impersonated_bank && (
              <div className="bg-slate-900 rounded-lg p-3">
                <p className="text-slate-500 text-xs mb-1">Bank Impersonated</p>
                <p className="text-red-400 text-sm font-medium">{report.impersonated_bank}</p>
              </div>
            )}
            <div className="bg-slate-900 rounded-lg p-3">
              <p className="text-slate-500 text-xs mb-1">Language</p>
              <p className="text-white text-sm font-medium capitalize">{report.language_detected}</p>
            </div>
            <div className="bg-slate-900 rounded-lg p-3">
              <p className="text-slate-500 text-xs mb-1">Source</p>
              <p className="text-white text-sm font-medium capitalize">{report.source}</p>
            </div>
          </div>

          {/* Explanation */}
          {report.explanation && (
            <div className="bg-slate-900 rounded-lg p-4 mb-4">
              <p className="text-slate-400 text-xs uppercase tracking-wide mb-2">
                📝 AI Analysis
              </p>
              <p className="text-slate-300 text-sm leading-relaxed">{report.explanation}</p>
            </div>
          )}

          {/* Red flags */}
          {report.red_flags && report.red_flags.length > 0 && (
            <div className="mb-4">
              <p className="text-slate-400 text-xs uppercase tracking-wide mb-2">
                🚩 Red Flags ({report.red_flags.length})
              </p>
              <div className="flex flex-wrap gap-2">
                {report.red_flags.map((flag, i) => (
                  <span
                    key={i}
                    className="px-3 py-1 bg-red-950 border border-red-800 rounded-full text-red-400 text-xs"
                  >
                    ⚠ {flag}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Recommended action */}
          {report.recommended_action && (
            <div className="bg-amber-950 border border-amber-800 rounded-lg p-4">
              <p className="text-amber-400 text-xs uppercase tracking-wide mb-2">
                ✅ What To Do
              </p>
              <p className="text-amber-200 text-sm leading-relaxed">{report.recommended_action}</p>
            </div>
          )}
        </div>

        {/* Share Section */}
        <div className="bg-slate-800 border border-slate-700 rounded-xl p-4 mb-6">
          <p className="text-white font-medium mb-3">⚠️ Warn your contacts</p>
          <p className="text-slate-400 text-sm mb-3">
            Share this report link to warn others about this scam pattern
          </p>
          <div className="flex gap-2">
            <input
              readOnly
              value={window.location.href}
              className="flex-1 bg-slate-900 border border-slate-600 rounded-lg px-3 py-2 text-slate-300 text-sm"
            />
            <button
              onClick={handleCopyLink}
              className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors whitespace-nowrap"
            >
              {copied ? "✓ Copied!" : "Copy Link"}
            </button>
          </div>
        </div>

        {/* CTA at bottom */}
        <div className="text-center">
          <p className="text-slate-400 text-sm mb-4">
            Check if your own messages are safe
          </p>
          <Link
            to="/check"
            className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-xl font-medium transition-colors"
          >
            Check a Message Now
          </Link>
        </div>
      </div>
    </main>
  );
}

export default ReportPage;